### ISSUE TITLE
Solver availability in control and internal wrapper

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-openfoam#60] opened 2015-12-17 15:07 UTC
By setting CUBAExt.INCOMPRESSIBLE, CUBAExt.LAMINAR_MODEL in the poiseuille example of the fileIO-control wrapper, simpleFoam is used internally to solve the problem. On the other hand, pimpleFoam is applied (by default) for the poiseuille example of the internal wrapper, when the same setting is given.

It would be great, if the same set of OpenFoam solvers (i.e. simpleFoam, pimpleFoam, interFoam) were suported by both wrapper types in the new version (Migration to OF2.4).

**Comment by santiagomarquezd** [comment] 2015-12-17 15:17
Hi @TobiasRasp, each solver requires a particular wrapping strategy and the original task was set to work with laminar incompressible and mixture. Our decision for pimpleFoam was due to the problem is transient and several PISO corrections are required in each time-step, which in simpleFoam are not available. I suppose that @khiltunen was focused in the stationary solution for the poiseuille case.

**Comment by TobiasRasp** [comment] 2015-12-17 15:32
I agree on the need for a transient solver and pimpleFoam is absolutely fine for me! My point is more about the fact that pimpleFoam is not supported in the IOcontrolwrapper (or vice versa simpleFoam is not supported in the internal wrapper). And it is a bit confusing that the identical input example triggers two different solvers (pimple for internal / simple for control wrapper) when currently switching between both wrapper versions.

**Comment by khiltunen** [comment] 2015-12-18 06:09
@TobiasRasp this will be fixed on the migration to OF2.4. Default solver will be pimpleFoam also on IO wrapper.

**Comment by khiltunen** [comment] 2016-01-18 14:35
Fixed in v 0.2.0

**Closed by khiltunen** 2016-01-18 14:35 UTC
